CREATE TRIGGER maj_salaire_professeurs --creation du trigger
BEFORE UPDATE ON PROFESSEURS --implation du trigger avant|apres l'insertion|modification|suppression
FOR EACH ROW
WHEN (:new.SALAIRE_ACTUEL < :old.SALAIRE_BASE) --condition d'erreur
DECLARE e EXCEPTION
BEGIN 
RAISE e 
EXCEPTION
WHEN e THEN RAISE_APPLICATION (2003,"message d'erreur") --erreur
END;



CREATE TRIGGER maj_auto
AFTER UPDATE OR INSERT OR DELETE ON PROFESSEURS
FOR EACH ROW
BEGIN

IF INSERTING THEN
INSERT INTO PROFESSEURS_spe VALUES(:new.NOM,:new.SPECIALITE,:new.DATE_ENTREE,:new.DER_PROM,:new.SALAIRE_BASE,:new.SALAIRE_ACTUEL);
END IF;

IF UPDATING THEN
UPDATE INTO PROFESSEURS
SET NOM = :new.NOM, SPECIALITE = :new.SPECIALITE, DATE_ENTREE = :new.DATE_ENTREE, DER_PROM = :new.DER_PROM, SALAIRE_BASE = :new.SALAIRE_BASE, SALAIRE_ACTUEL = :new.SALAIRE_ACTUEL;
END IF;

IF DELETING THEN
DELETE FROM PROFESSEURS
END IF;

END;


CREATE TRIGGER autoMAj
AFTER UPDATE OR DELETE ON PROFESSEURS
FOR EACH ROW
BEGIN

IF UPDATING THEN
UPDATE CHARGE
SET NUM_PROF = :new.NUM_PROF WHERE NUM_PROF = :old.NUM_PROF;
END  IF; 

IF DELETING THEN
DELETE FROM CHARGE WHERE NUM_PROF = :old.NUM_PROF; 
END IF;

END;
/

CREATE TRIGGER majAuditResultat
AFTER UPDATE ON RESULTATS
FOR EACH ROW
BEGI
NINSERT INTO AUDIT_RESULTATS VALUES (USER, SYSDATE, 'NOUVEAU', :new.NUM_ELEVE, :new.NUM_COURS, :new.POINTS ) ;
END;
/  